export const GET_ALL_ACCESS_CODES = 'GET_ALL_ACCESS_CODES';
export const REQUEST_ACCESS_START = 'REQUEST_ACCESS_START';
export const REQUEST_ACCESS_SUCCESS = 'REQUEST_ACCESS_SUCCESS';
export const REQUEST_ACCESS_FAILURE = 'REQUEST_ACCESS_FAILURE';
export const ACCESS_FAILURE = 'ACCESS_FAILURE';
export const ACCESS_SUCCESS = 'ACCESS_SUCCESS';

// actionTypes for actions
